name: Lint CloudFormation Templates

on:
  push:
    branches:
      - main
      - test

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Linter install
        uses: scottbrenner/cfn-lint-action@v2

      - name: Print the CloudFormation Linter Version & Run Linter.
        run: |
          cfn-lint --version
          cfn-lint -t ./*.yaml
        continue-on-error: true
